# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from formlabs_local_api.models.fleet_control_printer_group import FleetControlPrinterGroup
from formlabs_local_api.models.form2_printer import Form2Printer
from formlabs_local_api.models.form3_printer import Form3Printer
from formlabs_local_api.models.form4_printer import Form4Printer
from formlabs_local_api.models.fuse11_printer import Fuse11Printer
from formlabs_local_api.models.generic_device import GenericDevice
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DEVICESTATUSMODEL_ONE_OF_SCHEMAS = ["FleetControlPrinterGroup", "Form2Printer", "Form3Printer", "Form4Printer", "Fuse11Printer", "GenericDevice"]

class DeviceStatusModel(BaseModel):
    """
    DeviceStatusModel
    """
    # data type: GenericDevice
    oneof_schema_1_validator: Optional[GenericDevice] = None
    # data type: FleetControlPrinterGroup
    oneof_schema_2_validator: Optional[FleetControlPrinterGroup] = None
    # data type: Form4Printer
    oneof_schema_3_validator: Optional[Form4Printer] = None
    # data type: Form3Printer
    oneof_schema_4_validator: Optional[Form3Printer] = None
    # data type: Fuse11Printer
    oneof_schema_5_validator: Optional[Fuse11Printer] = None
    # data type: Form2Printer
    oneof_schema_6_validator: Optional[Form2Printer] = None
    actual_instance: Optional[Union[FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice]] = None
    one_of_schemas: Set[str] = { "FleetControlPrinterGroup", "Form2Printer", "Form3Printer", "Form4Printer", "Fuse11Printer", "GenericDevice" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DeviceStatusModel.model_construct()
        error_messages = []
        match = 0
        # validate data type: GenericDevice
        if not isinstance(v, GenericDevice):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenericDevice`")
        else:
            match += 1
        # validate data type: FleetControlPrinterGroup
        if not isinstance(v, FleetControlPrinterGroup):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FleetControlPrinterGroup`")
        else:
            match += 1
        # validate data type: Form4Printer
        if not isinstance(v, Form4Printer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Form4Printer`")
        else:
            match += 1
        # validate data type: Form3Printer
        if not isinstance(v, Form3Printer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Form3Printer`")
        else:
            match += 1
        # validate data type: Fuse11Printer
        if not isinstance(v, Fuse11Printer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Fuse11Printer`")
        else:
            match += 1
        # validate data type: Form2Printer
        if not isinstance(v, Form2Printer):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Form2Printer`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DeviceStatusModel with oneOf schemas: FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DeviceStatusModel with oneOf schemas: FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GenericDevice
        try:
            instance.actual_instance = GenericDevice.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FleetControlPrinterGroup
        try:
            instance.actual_instance = FleetControlPrinterGroup.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Form4Printer
        try:
            instance.actual_instance = Form4Printer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Form3Printer
        try:
            instance.actual_instance = Form3Printer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Fuse11Printer
        try:
            instance.actual_instance = Fuse11Printer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Form2Printer
        try:
            instance.actual_instance = Form2Printer.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DeviceStatusModel with oneOf schemas: FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DeviceStatusModel with oneOf schemas: FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FleetControlPrinterGroup, Form2Printer, Form3Printer, Form4Printer, Fuse11Printer, GenericDevice]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


