# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from formlabs_local_api.models.material_usage_model import MaterialUsageModel
from formlabs_local_api.models.model_properties import ModelProperties
from formlabs_local_api.models.scene_type_model import SceneTypeModel
from typing import Optional, Set
from typing_extensions import Self

class SceneModel(BaseModel):
    """
    SceneModel
    """ # noqa: E501
    models: Optional[List[ModelProperties]] = None
    scene_type: Optional[SceneTypeModel] = None
    material_usage: Optional[MaterialUsageModel] = None
    layer_count: Optional[StrictInt] = Field(default=None, description="The number of layers in the scene")
    __properties: ClassVar[List[str]] = ["models", "scene_type", "material_usage", "layer_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SceneModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in models (list)
        _items = []
        if self.models:
            for _item_models in self.models:
                if _item_models:
                    _items.append(_item_models.to_dict())
            _dict['models'] = _items
        # override the default output from pydantic by calling `to_dict()` of scene_type
        if self.scene_type:
            _dict['scene_type'] = self.scene_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of material_usage
        if self.material_usage:
            _dict['material_usage'] = self.material_usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SceneModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "models": [ModelProperties.from_dict(_item) for _item in obj["models"]] if obj.get("models") is not None else None,
            "scene_type": SceneTypeModel.from_dict(obj["scene_type"]) if obj.get("scene_type") is not None else None,
            "material_usage": MaterialUsageModel.from_dict(obj["material_usage"]) if obj.get("material_usage") is not None else None,
            "layer_count": obj.get("layer_count")
        })
        return _obj


