# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from formlabs_local_api.models.scene_type_model_layer_thickness_mm import SceneTypeModelLayerThicknessMm
from typing import Optional, Set
from typing_extensions import Self

class SceneTypeModel(BaseModel):
    """
    SceneTypeModel
    """ # noqa: E501
    machine_type: StrictStr = Field(description="The machine type of the scene")
    material_code: StrictStr = Field(description="The material code of the scene")
    print_setting: Optional[StrictStr] = Field(default=None, description="The print setting of the scene")
    layer_thickness_mm: SceneTypeModelLayerThicknessMm
    __properties: ClassVar[List[str]] = ["machine_type", "material_code", "print_setting", "layer_thickness_mm"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SceneTypeModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of layer_thickness_mm
        if self.layer_thickness_mm:
            _dict['layer_thickness_mm'] = self.layer_thickness_mm.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SceneTypeModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "machine_type": obj.get("machine_type"),
            "material_code": obj.get("material_code"),
            "print_setting": obj.get("print_setting"),
            "layer_thickness_mm": SceneTypeModelLayerThicknessMm.from_dict(obj["layer_thickness_mm"]) if obj.get("layer_thickness_mm") is not None else None
        })
        return _obj


