# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from formlabs_local_api.models.models_selection_model import ModelsSelectionModel
from typing import Optional, Set
from typing_extensions import Self

class SceneSaveScreenshotPostRequest(BaseModel):
    """
    SceneSaveScreenshotPostRequest
    """ # noqa: E501
    file: Annotated[str, Field(strict=True)] = Field(description="The file path to save the .png screenshot to")
    view_type: Optional[StrictStr] = Field(default='ZOOM_ON_MODELS', description="The type of view to use when taking the screenshot")
    models: Optional[ModelsSelectionModel] = None
    __properties: ClassVar[List[str]] = ["file", "view_type", "models"]

    @field_validator('file')
    def file_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^.*\.png$", value):
            raise ValueError(r"must validate the regular expression /^.*\.png$/")
        return value

    @field_validator('view_type')
    def view_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ZOOM_ON_MODELS', 'FULL_BUILD_VOLUME', 'FULL_PLATFORM_WIDTH']):
            raise ValueError("must be one of enum values ('ZOOM_ON_MODELS', 'FULL_BUILD_VOLUME', 'FULL_PLATFORM_WIDTH')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SceneSaveScreenshotPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of models
        if self.models:
            _dict['models'] = self.models.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SceneSaveScreenshotPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file": obj.get("file"),
            "view_type": obj.get("view_type") if obj.get("view_type") is not None else 'ZOOM_ON_MODELS',
            "models": ModelsSelectionModel.from_dict(obj["models"]) if obj.get("models") is not None else None
        })
        return _obj


