# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.scene_save_screenshot_post_request import SceneSaveScreenshotPostRequest

class TestSceneSaveScreenshotPostRequest(unittest.TestCase):
    """SceneSaveScreenshotPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneSaveScreenshotPostRequest:
        """Test SceneSaveScreenshotPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneSaveScreenshotPostRequest`
        """
        model = SceneSaveScreenshotPostRequest()
        if include_optional:
            return SceneSaveScreenshotPostRequest(
                file = 'jUR,rZ#UM/?R,Fp^l6$ARj.png',
                view_type = 'ZOOM_ON_MODELS',
                models = None
            )
        else:
            return SceneSaveScreenshotPostRequest(
                file = 'jUR,rZ#UM/?R,Fp^l6$ARj.png',
        )
        """

    def testSceneSaveScreenshotPostRequest(self):
        """Test SceneSaveScreenshotPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
