# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.form4_printer_cartridge_data_value import Form4PrinterCartridgeDataValue

class TestForm4PrinterCartridgeDataValue(unittest.TestCase):
    """Form4PrinterCartridgeDataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Form4PrinterCartridgeDataValue:
        """Test Form4PrinterCartridgeDataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Form4PrinterCartridgeDataValue`
        """
        model = Form4PrinterCartridgeDataValue()
        if include_optional:
            return Form4PrinterCartridgeDataValue(
                cartridge_material_code = '',
                cartridge_estimated_volume_dispensed_m_l = 1.337,
                cartridge_original_volume_m_l = 1.337
            )
        else:
            return Form4PrinterCartridgeDataValue(
                cartridge_material_code = '',
                cartridge_estimated_volume_dispensed_m_l = 1.337,
                cartridge_original_volume_m_l = 1.337,
        )
        """

    def testForm4PrinterCartridgeDataValue(self):
        """Test Form4PrinterCartridgeDataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
