# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.scene_models_id_post_request import SceneModelsIdPostRequest

class TestSceneModelsIdPostRequest(unittest.TestCase):
    """SceneModelsIdPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneModelsIdPostRequest:
        """Test SceneModelsIdPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneModelsIdPostRequest`
        """
        model = SceneModelsIdPostRequest()
        if include_optional:
            return SceneModelsIdPostRequest(
                name = '',
                position = formlabs_local_api.models.scene_position_model.ScenePositionModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                orientation = formlabs_local_api.models.orientation_model.OrientationModel(),
                scale = 1.337,
                units = 'MILLIMETERS'
            )
        else:
            return SceneModelsIdPostRequest(
        )
        """

    def testSceneModelsIdPostRequest(self):
        """Test SceneModelsIdPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
