# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_devices_get(self) -> None:
        """Test case for devices_get

        """
        pass

    def test_devices_id_get(self) -> None:
        """Test case for devices_id_get

        """
        pass

    def test_discover_devices_post(self) -> None:
        """Test case for discover_devices_post

        """
        pass

    def test_load_form_post(self) -> None:
        """Test case for load_form_post

        """
        pass

    def test_login_post(self) -> None:
        """Test case for login_post

        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        """
        pass

    def test_scene_auto_layout_post(self) -> None:
        """Test case for scene_auto_layout_post

        """
        pass

    def test_scene_auto_orient_post(self) -> None:
        """Test case for scene_auto_orient_post

        """
        pass

    def test_scene_auto_pack_post(self) -> None:
        """Test case for scene_auto_pack_post

        """
        pass

    def test_scene_auto_support_post(self) -> None:
        """Test case for scene_auto_support_post

        """
        pass

    def test_scene_estimate_print_time_post(self) -> None:
        """Test case for scene_estimate_print_time_post

        """
        pass

    def test_scene_get(self) -> None:
        """Test case for scene_get

        """
        pass

    def test_scene_import_model_post(self) -> None:
        """Test case for scene_import_model_post

        """
        pass

    def test_scene_models_id_delete(self) -> None:
        """Test case for scene_models_id_delete

        """
        pass

    def test_scene_models_id_duplicate_post(self) -> None:
        """Test case for scene_models_id_duplicate_post

        """
        pass

    def test_scene_models_id_get(self) -> None:
        """Test case for scene_models_id_get

        """
        pass

    def test_scene_models_id_post(self) -> None:
        """Test case for scene_models_id_post

        """
        pass

    def test_scene_models_id_replace_post(self) -> None:
        """Test case for scene_models_id_replace_post

        """
        pass

    def test_scene_post(self) -> None:
        """Test case for scene_post

        """
        pass

    def test_scene_print_post(self) -> None:
        """Test case for scene_print_post

        """
        pass

    def test_scene_print_validation_get(self) -> None:
        """Test case for scene_print_validation_get

        """
        pass

    def test_scene_save_form_post(self) -> None:
        """Test case for scene_save_form_post

        """
        pass

    def test_scene_save_screenshot_post(self) -> None:
        """Test case for scene_save_screenshot_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
