# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.scene_models_id_replace_post200_response import SceneModelsIdReplacePost200Response

class TestSceneModelsIdReplacePost200Response(unittest.TestCase):
    """SceneModelsIdReplacePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SceneModelsIdReplacePost200Response:
        """Test SceneModelsIdReplacePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SceneModelsIdReplacePost200Response`
        """
        model = SceneModelsIdReplacePost200Response()
        if include_optional:
            return SceneModelsIdReplacePost200Response(
                warnings = [
                    ''
                    ],
                model_properties = formlabs_local_api.models.model_properties.ModelProperties(
                    id = '', 
                    name = '', 
                    position = formlabs_local_api.models.scene_position_model.ScenePositionModel(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, ), 
                    orientation = formlabs_local_api.models.euler_angles_model.EulerAnglesModel(
                        x = 1.337, 
                        y = 1.337, 
                        z = 1.337, ), 
                    scale = 1.337, 
                    units = 'MILLIMETERS', 
                    bounding_box = formlabs_local_api.models.model_properties_bounding_box.ModelProperties_bounding_box(
                        min_corner = formlabs_local_api.models.scene_position_model.ScenePositionModel(
                            x = 1.337, 
                            y = 1.337, 
                            z = 1.337, ), 
                        max_corner = , ), 
                    original_file = '', 
                    visible = True, 
                    has_supports = True, 
                    in_bounds = True, 
                    raw_mesh_hash = '', 
                    canonical_model_hash = '', )
            )
        else:
            return SceneModelsIdReplacePost200Response(
        )
        """

    def testSceneModelsIdReplacePost200Response(self):
        """Test SceneModelsIdReplacePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
