# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.form2_printer import Form2Printer

class TestForm2Printer(unittest.TestCase):
    """Form2Printer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Form2Printer:
        """Test Form2Printer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Form2Printer`
        """
        model = Form2Printer()
        if include_optional:
            return Form2Printer(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = '',
                estimated_print_time_remaining_ms = 56,
                tank_id = '',
                tank_material_code = '',
                cartridge_data = {
                    'key' : formlabs_local_api.models.form_4_printer_cartridge_data_value.Form_4_Printer_cartridge_data_value(
                        cartridge_material_code = '', 
                        cartridge_estimated_volume_dispensed_m_l = 1.337, 
                        cartridge_original_volume_m_l = 1.337, )
                    }
            )
        else:
            return Form2Printer(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = '',
                estimated_print_time_remaining_ms = 56,
                tank_id = '',
                tank_material_code = '',
                cartridge_data = {
                    'key' : formlabs_local_api.models.form_4_printer_cartridge_data_value.Form_4_Printer_cartridge_data_value(
                        cartridge_material_code = '', 
                        cartridge_estimated_volume_dispensed_m_l = 1.337, 
                        cartridge_original_volume_m_l = 1.337, )
                    },
        )
        """

    def testForm2Printer(self):
        """Test Form2Printer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
