# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.scene_print_post_request import ScenePrintPostRequest

class TestScenePrintPostRequest(unittest.TestCase):
    """ScenePrintPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScenePrintPostRequest:
        """Test ScenePrintPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScenePrintPostRequest`
        """
        model = ScenePrintPostRequest()
        if include_optional:
            return ScenePrintPostRequest(
                printer = '',
                job_name = ''
            )
        else:
            return ScenePrintPostRequest(
                printer = '',
        )
        """

    def testScenePrintPostRequest(self):
        """Test ScenePrintPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
