# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.model_properties_bounding_box import ModelPropertiesBoundingBox

class TestModelPropertiesBoundingBox(unittest.TestCase):
    """ModelPropertiesBoundingBox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelPropertiesBoundingBox:
        """Test ModelPropertiesBoundingBox
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelPropertiesBoundingBox`
        """
        model = ModelPropertiesBoundingBox()
        if include_optional:
            return ModelPropertiesBoundingBox(
                min_corner = formlabs_local_api.models.scene_position_model.ScenePositionModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                max_corner = formlabs_local_api.models.scene_position_model.ScenePositionModel(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, )
            )
        else:
            return ModelPropertiesBoundingBox(
        )
        """

    def testModelPropertiesBoundingBox(self):
        """Test ModelPropertiesBoundingBox"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
