# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.devices_get200_response import DevicesGet200Response

class TestDevicesGet200Response(unittest.TestCase):
    """DevicesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevicesGet200Response:
        """Test DevicesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevicesGet200Response`
        """
        model = DevicesGet200Response()
        if include_optional:
            return DevicesGet200Response(
                count = 56,
                devices = [
                    formlabs_local_api.models.device_status_model.DeviceStatusModel()
                    ]
            )
        else:
            return DevicesGet200Response(
        )
        """

    def testDevicesGet200Response(self):
        """Test DevicesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
