# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.fleet_control_printer_group import FleetControlPrinterGroup

class TestFleetControlPrinterGroup(unittest.TestCase):
    """FleetControlPrinterGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetControlPrinterGroup:
        """Test FleetControlPrinterGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetControlPrinterGroup`
        """
        model = FleetControlPrinterGroup()
        if include_optional:
            return FleetControlPrinterGroup(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'REMOTE',
                firmware_version = '',
                dashboard_group_id = '',
                dashboard_queue_id = ''
            )
        else:
            return FleetControlPrinterGroup(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'REMOTE',
                firmware_version = '',
                dashboard_group_id = '',
                dashboard_queue_id = '',
        )
        """

    def testFleetControlPrinterGroup(self):
        """Test FleetControlPrinterGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
