# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.form4_printer import Form4Printer

class TestForm4Printer(unittest.TestCase):
    """Form4Printer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Form4Printer:
        """Test Form4Printer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Form4Printer`
        """
        model = Form4Printer()
        if include_optional:
            return Form4Printer(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = '',
                is_remote_print_enabled = True,
                estimated_print_time_remaining_ms = 56,
                tank_id = '',
                tank_material_code = '',
                cartridge_data = {
                    'key' : formlabs_local_api.models.form_4_printer_cartridge_data_value.Form_4_Printer_cartridge_data_value(
                        cartridge_material_code = '', 
                        cartridge_estimated_volume_dispensed_m_l = 1.337, 
                        cartridge_original_volume_m_l = 1.337, )
                    },
                ready_to_print_now = True
            )
        else:
            return Form4Printer(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = '',
                is_remote_print_enabled = True,
                estimated_print_time_remaining_ms = 56,
                tank_id = '',
                tank_material_code = '',
                cartridge_data = {
                    'key' : formlabs_local_api.models.form_4_printer_cartridge_data_value.Form_4_Printer_cartridge_data_value(
                        cartridge_material_code = '', 
                        cartridge_estimated_volume_dispensed_m_l = 1.337, 
                        cartridge_original_volume_m_l = 1.337, )
                    },
                ready_to_print_now = True,
        )
        """

    def testForm4Printer(self):
        """Test Form4Printer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
