# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.import_units_model import ImportUnitsModel

class TestImportUnitsModel(unittest.TestCase):
    """ImportUnitsModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportUnitsModel(self):
        """Test ImportUnitsModel"""
        # inst = ImportUnitsModel()

if __name__ == '__main__':
    unittest.main()
