# coding: utf-8

"""
    PreForm API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_local_api.models.generic_device import GenericDevice

class TestGenericDevice(unittest.TestCase):
    """GenericDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericDevice:
        """Test GenericDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericDevice`
        """
        model = GenericDevice()
        if include_optional:
            return GenericDevice(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = ''
            )
        else:
            return GenericDevice(
                id = '',
                product_name = '',
                status = '',
                is_connected = True,
                connection_type = 'UNKNOWN',
                ip_address = '',
                firmware_version = '',
        )
        """

    def testGenericDevice(self):
        """Test GenericDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
