# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.printer_cartridge_status import PrinterCartridgeStatus

class TestPrinterCartridgeStatus(unittest.TestCase):
    """PrinterCartridgeStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrinterCartridgeStatus:
        """Test PrinterCartridgeStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrinterCartridgeStatus`
        """
        model = PrinterCartridgeStatus()
        if include_optional:
            return PrinterCartridgeStatus(
                cartridge = formlabs_web_api.models.cartridge_read_only.CartridgeReadOnly(
                    serial = '', 
                    material = '', 
                    initial_volume_ml = 1.337, 
                    volume_dispensed_ml = 1.337, 
                    display_name = '', 
                    is_empty = True, 
                    inside_printer = '', 
                    connected_group = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    machine_type_id = null, ),
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cartridge_slot = None
            )
        else:
            return PrinterCartridgeStatus(
                cartridge = formlabs_web_api.models.cartridge_read_only.CartridgeReadOnly(
                    serial = '', 
                    material = '', 
                    initial_volume_ml = 1.337, 
                    volume_dispensed_ml = 1.337, 
                    display_name = '', 
                    is_empty = True, 
                    inside_printer = '', 
                    connected_group = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    machine_type_id = null, ),
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPrinterCartridgeStatus(self):
        """Test PrinterCartridgeStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
