# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.api.prints_api import PrintsApi


class TestPrintsApi(unittest.TestCase):
    """PrintsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrintsApi()

    def tearDown(self) -> None:
        pass

    def test_prints_list(self) -> None:
        """Test case for prints_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
