# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.printer_tank_status import PrinterTankStatus

class TestPrinterTankStatus(unittest.TestCase):
    """PrinterTankStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrinterTankStatus:
        """Test PrinterTankStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrinterTankStatus`
        """
        model = PrinterTankStatus()
        if include_optional:
            return PrinterTankStatus(
                tank = formlabs_web_api.models.tank_read_only.TankReadOnly(
                    serial = '', 
                    material = '', 
                    print_time_ms = 56, 
                    layers_printed = 56, 
                    first_fill_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    heatmap = '', 
                    heatmap_gif = '', 
                    display_name = '', 
                    layer_count = 56, 
                    inside_printer = '', 
                    tank_type = '', 
                    connected_group = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PrinterTankStatus(
                tank = formlabs_web_api.models.tank_read_only.TankReadOnly(
                    serial = '', 
                    material = '', 
                    print_time_ms = 56, 
                    layers_printed = 56, 
                    first_fill_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    heatmap = '', 
                    heatmap_gif = '', 
                    display_name = '', 
                    layer_count = 56, 
                    inside_printer = '', 
                    tank_type = '', 
                    connected_group = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPrinterTankStatus(self):
        """Test PrinterTankStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
