# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.developer_apimy_printer_machine_type_id_enum import DeveloperAPIMyPrinterMachineTypeIdEnum

class TestDeveloperAPIMyPrinterMachineTypeIdEnum(unittest.TestCase):
    """DeveloperAPIMyPrinterMachineTypeIdEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeveloperAPIMyPrinterMachineTypeIdEnum(self):
        """Test DeveloperAPIMyPrinterMachineTypeIdEnum"""
        # inst = DeveloperAPIMyPrinterMachineTypeIdEnum()

if __name__ == '__main__':
    unittest.main()
