# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_create(self) -> None:
        """Test case for groups_create

        """
        pass

    def test_groups_destroy(self) -> None:
        """Test case for groups_destroy

        """
        pass

    def test_groups_list(self) -> None:
        """Test case for groups_list

        """
        pass

    def test_groups_members_create(self) -> None:
        """Test case for groups_members_create

        """
        pass

    def test_groups_members_destroy(self) -> None:
        """Test case for groups_members_destroy

        """
        pass

    def test_groups_members_update(self) -> None:
        """Test case for groups_members_update

        """
        pass

    def test_groups_partial_update(self) -> None:
        """Test case for groups_partial_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
