# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.paginated_developer_apimy_printer_list import PaginatedDeveloperAPIMyPrinterList

class TestPaginatedDeveloperAPIMyPrinterList(unittest.TestCase):
    """PaginatedDeveloperAPIMyPrinterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedDeveloperAPIMyPrinterList:
        """Test PaginatedDeveloperAPIMyPrinterList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedDeveloperAPIMyPrinterList`
        """
        model = PaginatedDeveloperAPIMyPrinterList()
        if include_optional:
            return PaginatedDeveloperAPIMyPrinterList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    formlabs_web_api.models.developer_apimy_printer.DeveloperAPIMyPrinter(
                        serial = '', 
                        machine_type_id = null, 
                        total_print_time_ms = 56, 
                        total_number_of_prints = null, 
                        printer_status = null, 
                        cartridge_status = null, 
                        tank_status = null, 
                        group = null, 
                        previous_print_run = {
                            'key' : null
                            }, 
                        firmware_version = '', 
                        location = '', )
                    ]
            )
        else:
            return PaginatedDeveloperAPIMyPrinterList(
        )
        """

    def testPaginatedDeveloperAPIMyPrinterList(self):
        """Test PaginatedDeveloperAPIMyPrinterList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
