# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.tank_read_only import TankReadOnly

class TestTankReadOnly(unittest.TestCase):
    """TankReadOnly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TankReadOnly:
        """Test TankReadOnly
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TankReadOnly`
        """
        model = TankReadOnly()
        if include_optional:
            return TankReadOnly(
                serial = '',
                material = '',
                print_time_ms = 56,
                layers_printed = 56,
                first_fill_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                heatmap = '',
                heatmap_gif = '',
                display_name = '',
                layer_count = 56,
                inside_printer = '',
                tank_type = '',
                connected_group = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TankReadOnly(
                serial = '',
                material = '',
                print_time_ms = 56,
                layers_printed = 56,
                first_fill_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                heatmap_gif = '',
                layer_count = 56,
                inside_printer = '',
                tank_type = '',
                connected_group = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_print_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTankReadOnly(self):
        """Test TankReadOnly"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
