# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.paginated_workgroup_list import PaginatedWorkgroupList

class TestPaginatedWorkgroupList(unittest.TestCase):
    """PaginatedWorkgroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedWorkgroupList:
        """Test PaginatedWorkgroupList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedWorkgroupList`
        """
        model = PaginatedWorkgroupList()
        if include_optional:
            return PaginatedWorkgroupList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    formlabs_web_api.models.workgroup.Workgroup(
                        id = '', 
                        name = '', 
                        remote_print_enabled_override = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        memberships = [
                            formlabs_web_api.models.workgroup_membership.WorkgroupMembership(
                                is_admin = True, 
                                user = '', 
                                email = '', 
                                username = '', 
                                user_id = '', 
                                first_name = '', 
                                last_name = '', )
                            ], 
                        printers = [
                            ''
                            ], 
                        invitations = [
                            formlabs_web_api.models.group_invitation.GroupInvitation(
                                email = '', 
                                is_admin = True, )
                            ], 
                        has_fleet_control = True, 
                        has_fleet_control_updated_by = 56, 
                        settings = null, )
                    ]
            )
        else:
            return PaginatedWorkgroupList(
        )
        """

    def testPaginatedWorkgroupList(self):
        """Test PaginatedWorkgroupList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
