# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.api.printers_api import PrintersApi


class TestPrintersApi(unittest.TestCase):
    """PrintersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrintersApi()

    def tearDown(self) -> None:
        pass

    def test_printers_list(self) -> None:
        """Test case for printers_list

        """
        pass

    def test_printers_prints_list(self) -> None:
        """Test case for printers_prints_list

        """
        pass

    def test_printers_retrieve(self) -> None:
        """Test case for printers_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
