# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.camera_status_enum import CameraStatusEnum

class TestCameraStatusEnum(unittest.TestCase):
    """CameraStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCameraStatusEnum(self):
        """Test CameraStatusEnum"""
        # inst = CameraStatusEnum()

if __name__ == '__main__':
    unittest.main()
