# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.my_deep_printer_status import MyDeepPrinterStatus

class TestMyDeepPrinterStatus(unittest.TestCase):
    """MyDeepPrinterStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MyDeepPrinterStatus:
        """Test MyDeepPrinterStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MyDeepPrinterStatus`
        """
        model = MyDeepPrinterStatus()
        if include_optional:
            return MyDeepPrinterStatus(
                status = '',
                last_pinged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hopper_level = -2147483648,
                material_credit = 1.337,
                hopper_material = '',
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_temperature = 1.337,
                current_print_run = formlabs_web_api.models.my_print_run_read_only.MyPrintRunReadOnly(
                    guid = '', 
                    name = '', 
                    printer = '', 
                    status = null, 
                    using_open_mode = True, 
                    z_height_offset_mm = 1.337, 
                    print_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    print_finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    layer_count = 56, 
                    volume_ml = 1.337, 
                    material = '', 
                    layer_thickness_mm = 1.337, 
                    currently_printing_layer = 56, 
                    estimated_duration_ms = 56, 
                    elapsed_duration_ms = 56, 
                    estimated_time_remaining_ms = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    print_run_success = null, 
                    feedback = null, 
                    firmware_version = '', 
                    cartridge = '', 
                    front_cartridge = '', 
                    back_cartridge = '', 
                    tank = '', 
                    cylinder = '', 
                    note = null, 
                    print_thumbnail = null, 
                    post_print_photo_url = '', 
                    user = null, 
                    user_custom_label = '', 
                    group = null, 
                    adaptive_thickness = True, 
                    probably_finished = True, 
                    message = '', 
                    print_job = '', 
                    material_name = '', 
                    print_settings_name = '', 
                    print_settings_code = '', 
                    form_auto_serial = '', 
                    form_auto_fw_version = '', 
                    harvest_status = 'FORM_CELL_HARVEST_UNKNOWN', ),
                form_cell = formlabs_web_api.models.form_cell.FormCell(
                    serial = '', 
                    firmware_version = '', 
                    status = '', 
                    rotation = '', ),
                last_printer_cooldown_started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                outer_boundary_offset_corrections = None,
                build_platform_contents = 'BUILD_PLATFORM_CONTENTS_NOT_SUPPORTED',
                tank_mixer_state = 'TANK_MIXER_STATE_NOT_SUPPORTED',
                ready_to_print = 'READY_TO_PRINT_NOT_SUPPORTED',
                printer_capabilities = [
                    ''
                    ],
                printernet_capabilities = [
                    ''
                    ],
                camera_status = 'UNKNOWN'
            )
        else:
            return MyDeepPrinterStatus(
                status = '',
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                current_print_run = formlabs_web_api.models.my_print_run_read_only.MyPrintRunReadOnly(
                    guid = '', 
                    name = '', 
                    printer = '', 
                    status = null, 
                    using_open_mode = True, 
                    z_height_offset_mm = 1.337, 
                    print_started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    print_finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    layer_count = 56, 
                    volume_ml = 1.337, 
                    material = '', 
                    layer_thickness_mm = 1.337, 
                    currently_printing_layer = 56, 
                    estimated_duration_ms = 56, 
                    elapsed_duration_ms = 56, 
                    estimated_time_remaining_ms = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    print_run_success = null, 
                    feedback = null, 
                    firmware_version = '', 
                    cartridge = '', 
                    front_cartridge = '', 
                    back_cartridge = '', 
                    tank = '', 
                    cylinder = '', 
                    note = null, 
                    print_thumbnail = null, 
                    post_print_photo_url = '', 
                    user = null, 
                    user_custom_label = '', 
                    group = null, 
                    adaptive_thickness = True, 
                    probably_finished = True, 
                    message = '', 
                    print_job = '', 
                    material_name = '', 
                    print_settings_name = '', 
                    print_settings_code = '', 
                    form_auto_serial = '', 
                    form_auto_fw_version = '', 
                    harvest_status = 'FORM_CELL_HARVEST_UNKNOWN', ),
                form_cell = formlabs_web_api.models.form_cell.FormCell(
                    serial = '', 
                    firmware_version = '', 
                    status = '', 
                    rotation = '', ),
        )
        """

    def testMyDeepPrinterStatus(self):
        """Test MyDeepPrinterStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
