# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from formlabs_web_api.models.print_run_success_enum import PrintRunSuccessEnum

class TestPrintRunSuccessEnum(unittest.TestCase):
    """PrintRunSuccessEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrintRunSuccessEnum(self):
        """Test PrintRunSuccessEnum"""
        # inst = PrintRunSuccessEnum()

if __name__ == '__main__':
    unittest.main()
