# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BuildPlatformContentsEnum(str, Enum):
    """
    * `BUILD_PLATFORM_CONTENTS_NOT_SUPPORTED` - NotSupported * `BUILD_PLATFORM_CONTENTS_MISSING` - Missing * `BUILD_PLATFORM_CONTENTS_UNCONFIRMED` - Unconfirmed * `BUILD_PLATFORM_CONTENTS_CONFIRMED_CLEAR` - ConfirmedClear * `BUILD_PLATFORM_CONTENTS_CONFIRMED_DIRTY` - ConfirmedDirty * `BUILD_PLATFORM_CONTENTS_POST_PRINT` - PostPrint
    """

    """
    allowed enum values
    """
    BUILD_PLATFORM_CONTENTS_NOT_SUPPORTED = 'BUILD_PLATFORM_CONTENTS_NOT_SUPPORTED'
    BUILD_PLATFORM_CONTENTS_MISSING = 'BUILD_PLATFORM_CONTENTS_MISSING'
    BUILD_PLATFORM_CONTENTS_UNCONFIRMED = 'BUILD_PLATFORM_CONTENTS_UNCONFIRMED'
    BUILD_PLATFORM_CONTENTS_CONFIRMED_CLEAR = 'BUILD_PLATFORM_CONTENTS_CONFIRMED_CLEAR'
    BUILD_PLATFORM_CONTENTS_CONFIRMED_DIRTY = 'BUILD_PLATFORM_CONTENTS_CONFIRMED_DIRTY'
    BUILD_PLATFORM_CONTENTS_POST_PRINT = 'BUILD_PLATFORM_CONTENTS_POST_PRINT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BuildPlatformContentsEnum from a JSON string"""
        return cls(json.loads(json_str))


