# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeveloperAPIMyPrinterMachineTypeIdEnum(str, Enum):
    """
    DeveloperAPIMyPrinterMachineTypeIdEnum
    """

    """
    allowed enum values
    """
    FORM_MINUS_1_MINUS_0 = 'FORM-1-0'
    FORM_MINUS_1_MINUS_1 = 'FORM-1-1'
    FORM_MINUS_2_MINUS_0 = 'FORM-2-0'
    FORM_MINUS_2_MINUS_1 = 'FORM-2-1'
    FORM_MINUS_3_MINUS_0 = 'FORM-3-0'
    FORM_MINUS_3_MINUS_1 = 'FORM-3-1'
    FORM_MINUS_3_MINUS_2 = 'FORM-3-2'
    DGJR_MINUS_1_MINUS_0 = 'DGJR-1-0'
    FRML_MINUS_3_MINUS_0 = 'FRML-3-0'
    FRBL_MINUS_3_MINUS_0 = 'FRBL-3-0'
    FRMB_MINUS_3_MINUS_0 = 'FRMB-3-0'
    DGSR_MINUS_1_MINUS_0 = 'DGSR-1-0'
    FRMB_MINUS_3_MINUS_1 = 'FRMB-3-1'
    PILK_MINUS_1_MINUS_0 = 'PILK-1-0'
    SIFT_MINUS_1 = 'SIFT-1'
    UNKNOWN = 'UNKNOWN'
    PILK_MINUS_1_MINUS_1 = 'PILK-1-1'
    SIFT_MINUS_1_MINUS_0 = 'SIFT-1-0'
    SIFT_MINUS_1_MINUS_1 = 'SIFT-1-1'
    CURL_MINUS_1_MINUS_1 = 'CURL-1-1'
    CURL_MINUS_1_MINUS_0 = 'CURL-1-0'
    WSHL_MINUS_1_MINUS_0 = 'WSHL-1-0'
    FS30_MINUS_1_MINUS_0 = 'FS30-1-0'
    FS30_MINUS_1_MINUS_1 = 'FS30-1-1'
    FORM_MINUS_4_MINUS_0 = 'FORM-4-0'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeveloperAPIMyPrinterMachineTypeIdEnum from a JSON string"""
        return cls(json.loads(json_str))


