# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HarvestStatusEnum(str, Enum):
    """
    * `FORM_CELL_HARVEST_UNKNOWN` - Unknown * `FORM_CELL_HARVEST_STARTED` - Started * `FORM_CELL_HARVEST_FINISHED` - Finished * `FORM_CELL_HARVEST_FAILED` - Print Failed * `FORM_CELL_HARVEST_ABORTED` - Aborted
    """

    """
    allowed enum values
    """
    FORM_CELL_HARVEST_UNKNOWN = 'FORM_CELL_HARVEST_UNKNOWN'
    FORM_CELL_HARVEST_STARTED = 'FORM_CELL_HARVEST_STARTED'
    FORM_CELL_HARVEST_FINISHED = 'FORM_CELL_HARVEST_FINISHED'
    FORM_CELL_HARVEST_FAILED = 'FORM_CELL_HARVEST_FAILED'
    FORM_CELL_HARVEST_ABORTED = 'FORM_CELL_HARVEST_ABORTED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HarvestStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


