# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PrintRunSuccessEnum(str, Enum):
    """
    * `UNKNOWN` - Unknown * `SUCCESS` - Success * `FAILURE` - Failure
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PrintRunSuccessEnum from a JSON string"""
        return cls(json.loads(json_str))


