# coding: utf-8

"""
    Formlabs Developer API

    The Formlabs Dashboard Developer API provides resources to integrate Formlabs products into customer’s workflow and existing systems

    The version of the OpenAPI document: 0.1.0
    Contact: api-inquiry@formlabs.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TankMixerStateEnum(str, Enum):
    """
    * `TANK_MIXER_STATE_NOT_SUPPORTED` - Notsupported * `TANK_MIXER_STATE_PRESENT` - Present * `TANK_MIXER_STATE_UNCONFIRMED` - Unconfirmed * `TANK_MIXER_STATE_MISSING` - Missing
    """

    """
    allowed enum values
    """
    TANK_MIXER_STATE_NOT_SUPPORTED = 'TANK_MIXER_STATE_NOT_SUPPORTED'
    TANK_MIXER_STATE_PRESENT = 'TANK_MIXER_STATE_PRESENT'
    TANK_MIXER_STATE_UNCONFIRMED = 'TANK_MIXER_STATE_UNCONFIRMED'
    TANK_MIXER_STATE_MISSING = 'TANK_MIXER_STATE_MISSING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TankMixerStateEnum from a JSON string"""
        return cls(json.loads(json_str))


